class CreateCountries < ActiveRecord::Migration
  def self.up
    create_table :countries do |t|
      t.column :id,                      :int
      t.column :country_name,            :string
      t.column :country_code,            :string

      t.timestamps
    end
Country.create(:country_name => 'AFGHANISTAN',:country_code =>'AF')                                  
Country.create(:country_name => 'ALAND ISLANDS',:country_code =>'AX')                                
Country.create(:country_name => 'ALBANIA',:country_code =>'AL')                                      
Country.create(:country_name => 'ALGERIA',:country_code =>'DZ')                                      
Country.create(:country_name => 'AMERICAN SAMOA',:country_code =>'AS')                               
Country.create(:country_name => 'ANDORRA',:country_code =>'AD')                                      
Country.create(:country_name => 'ANGOLA',:country_code =>'AO')                                       
Country.create(:country_name => 'ANGUILLA',:country_code =>'AI')                                     
Country.create(:country_name => 'ANTARCTICA',:country_code =>'AQ')                                   
Country.create(:country_name => 'ANTIGUA AND BARBUDA',:country_code =>'AG')                          
Country.create(:country_name => 'ARGENTINA',:country_code =>'AR')                                    
Country.create(:country_name => 'ARMENIA',:country_code =>'AM')                                      
Country.create(:country_name => 'ARUBA',:country_code =>'AW')                                        
Country.create(:country_name => 'AUSTRALIA',:country_code =>'AU')                                    
Country.create(:country_name => 'AUSTRIA',:country_code =>'AT')                                      
Country.create(:country_name => 'AZERBAIJAN',:country_code =>'AZ')                                   
Country.create(:country_name => 'BAHAMAS',:country_code =>'BS')                                      
Country.create(:country_name => 'BAHRAIN',:country_code =>'BH')                                      
Country.create(:country_name => 'BANGLADESH',:country_code =>'BD')                                   
Country.create(:country_name => 'BARBADOS',:country_code =>'BB')                                     
Country.create(:country_name => 'BELARUS',:country_code =>'BY')                                      
Country.create(:country_name => 'BELGIUM',:country_code =>'BE')                                      
Country.create(:country_name => 'BELIZE',:country_code =>'BZ')                                       
Country.create(:country_name => 'BENIN',:country_code =>'BJ')                                        
Country.create(:country_name => 'BERMUDA',:country_code =>'BM')                                      
Country.create(:country_name => 'BHUTAN',:country_code =>'BT')                                       
Country.create(:country_name => 'BOLIVIA',:country_code =>'BO')                                      
Country.create(:country_name => 'BOSNIA & HERZEGOVINA',:country_code =>'BA')                         
Country.create(:country_name => 'BOTSWANA',:country_code =>'BW')                                     
Country.create(:country_name => 'BOUVET ISLAND',:country_code =>'BV')                                
Country.create(:country_name => 'BRAZIL',:country_code =>'BR')                                       
Country.create(:country_name => 'BRITISH INDIAN OCEAN TERR',:country_code =>'IO')                    
Country.create(:country_name => 'BRUNEI DARUSSALAM',:country_code =>'BN')                            
Country.create(:country_name => 'BULGARIA',:country_code =>'BG')                                     
Country.create(:country_name => 'BURKINA FASO',:country_code =>'BF')                                 
Country.create(:country_name => 'BURUNDI',:country_code =>'BI')                                      
Country.create(:country_name => 'CAMBODIA',:country_code =>'KH')                                     
Country.create(:country_name => 'CAMEROON',:country_code =>'CM')                                     
Country.create(:country_name => 'CANADA',:country_code =>'CA')                                       
Country.create(:country_name => 'CAPE VERDE',:country_code =>'CV')                                   
Country.create(:country_name => 'CAYMAN ISLANDS',:country_code =>'KY')                               
Country.create(:country_name => 'CENTRAL AFRICAN REPUBLIC',:country_code =>'CF')                     
Country.create(:country_name => 'CHAD',:country_code =>'TD')                                         
Country.create(:country_name => 'CHILE',:country_code =>'CL')                                        
Country.create(:country_name => 'CHINA',:country_code =>'CN')                                        
Country.create(:country_name => 'CHRISTMAS ISLAND',:country_code =>'CX')                             
Country.create(:country_name => 'COCOS ISLANDS',:country_code =>'CC')                                
Country.create(:country_name => 'COLOMBIA',:country_code =>'CO')                                     
Country.create(:country_name => 'COMOROS',:country_code =>'KM')                                      
Country.create(:country_name => 'CONGO',:country_code =>'CG')                                        
Country.create(:country_name => 'COOK ISLANDS',:country_code =>'CK')                                 
Country.create(:country_name => 'COSTA RICA',:country_code =>'CR')                                   
Country.create(:country_name => 'COUNTRY-UNKNOWN',:country_code =>'ZZ')                              
Country.create(:country_name => 'CROATIA',:country_code =>'HR')                                      
Country.create(:country_name => 'CYPRUS',:country_code =>'CY')                                       
Country.create(:country_name => 'CZECH REPUBLIC',:country_code =>'CZ')                               
Country.create(:country_name => 'C?TE D\'IVOIRE',:country_code =>'CI')                                
Country.create(:country_name => 'DENMARK',:country_code =>'DK')                                      
Country.create(:country_name => 'DJIBOUTI',:country_code =>'DJ')                                     
Country.create(:country_name => 'DOMINICA',:country_code =>'DM')                                     
Country.create(:country_name => 'DOMINICAN REPUBLIC',:country_code =>'DO')                           
Country.create(:country_name => 'ECUADOR',:country_code =>'EC')                                      
Country.create(:country_name => 'EGYPT',:country_code =>'EG')                                        
Country.create(:country_name => 'EL SALVADOR',:country_code =>'SV')                                  
Country.create(:country_name => 'EL SALVADOR',:country_code =>'EL')                                  
Country.create(:country_name => 'EQUATORIAL GUINEA',:country_code =>'GQ')                            
Country.create(:country_name => 'ERITREA',:country_code =>'ER')                                      
Country.create(:country_name => 'ESTONIA',:country_code =>'EE')                                      
Country.create(:country_name => 'ETHIOPIA',:country_code =>'ET')                                     
Country.create(:country_name => 'FALKLAND ISLANDS',:country_code =>'FK')                             
Country.create(:country_name => 'FAROE ISLANDS',:country_code =>'FO')                                
Country.create(:country_name => 'FIJI',:country_code =>'FJ')                                         
Country.create(:country_name => 'FINLAND',:country_code =>'FI')                                      
Country.create(:country_name => 'FRANCE',:country_code =>'FR')                                       
Country.create(:country_name => 'FRENCH GUIANA',:country_code =>'GF')                                
Country.create(:country_name => 'FRENCH POLYNESIA',:country_code =>'PF')                             
Country.create(:country_name => 'FRENCH SOUTHERN TERR',:country_code =>'TF')                         
Country.create(:country_name => 'GABON',:country_code =>'GA')                                        
Country.create(:country_name => 'GAMBIA',:country_code =>'GM')                                       
Country.create(:country_name => 'GEORGIA',:country_code =>'GE')                                      
Country.create(:country_name => 'GERMANY',:country_code =>'DE')                                      
Country.create(:country_name => 'GHANA',:country_code =>'GH')                                        
Country.create(:country_name => 'GIBRALTAR',:country_code =>'GI')                                    
Country.create(:country_name => 'GREECE',:country_code =>'GR')                                       
Country.create(:country_name => 'GREENLAND',:country_code =>'GL')                                    
Country.create(:country_name => 'GRENADA',:country_code =>'GD')                                      
Country.create(:country_name => 'GUADELOUPE',:country_code =>'GP')                                   
Country.create(:country_name => 'GUAM',:country_code =>'GU')                                         
Country.create(:country_name => 'GUATEMALA',:country_code =>'GT')                                    
Country.create(:country_name => 'GUERNSEY',:country_code =>'GG')                                     
Country.create(:country_name => 'GUINEA',:country_code =>'GN')                                       
Country.create(:country_name => 'GUINEA-BISSAU',:country_code =>'GW')                                
Country.create(:country_name => 'GUYANA',:country_code =>'GY')                                       
Country.create(:country_name => 'HAITI',:country_code =>'HT')                                        
Country.create(:country_name => 'HEARD ISLANDS & MCDONALD ISLDS',:country_code =>'HM')               
Country.create(:country_name => 'HOLLAND',:country_code =>'HL')                                      
Country.create(:country_name => 'HOLY SEE (VATICAN CITY STATE)',:country_code =>'VA')                
Country.create(:country_name => 'HONDURAS',:country_code =>'HN')                                     
Country.create(:country_name => 'HONG KONG',:country_code =>'HK')                                    
Country.create(:country_name => 'HUNGARY',:country_code =>'HU')                                      
Country.create(:country_name => 'ICELAND',:country_code =>'IS')                                      
Country.create(:country_name => 'INDIA',:country_code =>'IN')                                        
Country.create(:country_name => 'INDONESIA',:country_code =>'ID')                                    
Country.create(:country_name => 'IRAQ',:country_code =>'IQ')                                         
Country.create(:country_name => 'IRELAND',:country_code =>'IE')                                      
Country.create(:country_name => 'ISLE OF MAN',:country_code =>'IM')                                  
Country.create(:country_name => 'ISRAEL',:country_code =>'IL')                                       
Country.create(:country_name => 'ITALY',:country_code =>'IT')                                        
Country.create(:country_name => 'JAMAICA',:country_code =>'JM')                                      
Country.create(:country_name => 'JAPAN',:country_code =>'JP')                                        
Country.create(:country_name => 'JERSEY',:country_code =>'JE')                                       
Country.create(:country_name => 'JORDAN',:country_code =>'JO')                                       
Country.create(:country_name => 'KAZAKHSTAN',:country_code =>'KZ')                                   
Country.create(:country_name => 'KENYA',:country_code =>'KE')                                        
Country.create(:country_name => 'KIRIBATI',:country_code =>'KI')                                     
Country.create(:country_name => 'KOREA, REPUBLIC OF',:country_code =>'KR')                           
Country.create(:country_name => 'KUWAIT',:country_code =>'KW')                                       
Country.create(:country_name => 'KYRGYZSTAN',:country_code =>'KG')                                   
Country.create(:country_name => 'LAO PEOPLE\'S DEM REP',:country_code =>'LA')                         
Country.create(:country_name => 'LATVIA',:country_code =>'LV')                                       
Country.create(:country_name => 'LEBANON',:country_code =>'LB')                                      
Country.create(:country_name => 'LESOTHO',:country_code =>'LS')                                      
Country.create(:country_name => 'LIBERIA',:country_code =>'LR')                                      
Country.create(:country_name => 'LIBYA',:country_code =>'LY')                                        
Country.create(:country_name => 'LIECHTENSTEIN',:country_code =>'LI')                                
Country.create(:country_name => 'LITHUANIA',:country_code =>'LT')                                    
Country.create(:country_name => 'LUXEMBOURG',:country_code =>'LU')                                   
Country.create(:country_name => 'MACAO',:country_code =>'MO')                                        
Country.create(:country_name => 'MACEDONIA',:country_code =>'MK')                                    
Country.create(:country_name => 'MADAGASCAR',:country_code =>'MG')                                   
Country.create(:country_name => 'MALAWI',:country_code =>'MW')                                       
Country.create(:country_name => 'MALAYSIA',:country_code =>'MY')                                     
Country.create(:country_name => 'MALDIVES',:country_code =>'MV')                                     
Country.create(:country_name => 'MALI',:country_code =>'ML')                                         
Country.create(:country_name => 'MALTA',:country_code =>'MT')                                        
Country.create(:country_name => 'MARSHALL ISLANDS',:country_code =>'MH')                             
Country.create(:country_name => 'MARTINIQUE',:country_code =>'MQ')                                   
Country.create(:country_name => 'MAURITANIA',:country_code =>'MR')                                   
Country.create(:country_name => 'MAURITIUS',:country_code =>'MU')                                    
Country.create(:country_name => 'MAYOTTE',:country_code =>'YT')                                      
Country.create(:country_name => 'MEXICO',:country_code =>'MX')                                       
Country.create(:country_name => 'MICRONESIA, FED STATES OF',:country_code =>'FM')                    
Country.create(:country_name => 'MOLDOVA',:country_code =>'MD')                                      
Country.create(:country_name => 'MONACO',:country_code =>'MC')                                       
Country.create(:country_name => 'MONGOLIA',:country_code =>'MN')                                     
Country.create(:country_name => 'MONTENEGRO',:country_code =>'ME')                                   
Country.create(:country_name => 'MONTSERRAT',:country_code =>'MS')                                   
Country.create(:country_name => 'MOROCCO',:country_code =>'MA')                                      
Country.create(:country_name => 'MOZAMBIQUE',:country_code =>'MZ')                                   
Country.create(:country_name => 'MYANMAR',:country_code =>'MM')                                      
Country.create(:country_name => 'NAMIBIA',:country_code =>'NA')                                      
Country.create(:country_name => 'NAURU',:country_code =>'NR')                                        
Country.create(:country_name => 'NEPAL',:country_code =>'NP')                                        
Country.create(:country_name => 'NETHERLANDS',:country_code =>'NL')                                  
Country.create(:country_name => 'NETHERLANDS ANTILLES',:country_code =>'AN')                         
Country.create(:country_name => 'NEW CALEDONIA',:country_code =>'NC')                                
Country.create(:country_name => 'NEW ZEALAND',:country_code =>'NZ')                                  
Country.create(:country_name => 'NICARAGUA',:country_code =>'NI')                                    
Country.create(:country_name => 'NIGER',:country_code =>'NE')                                        
Country.create(:country_name => 'NIGERIA',:country_code =>'NG')                                      
Country.create(:country_name => 'NIUE',:country_code =>'NU')                                         
Country.create(:country_name => 'NORFOLK ISLAND',:country_code =>'NF')                               
Country.create(:country_name => 'NORTH KOREA',:country_code =>'KP')                                  
Country.create(:country_name => 'NORTHERN MARIANA ISLANDS',:country_code =>'MP')                     
Country.create(:country_name => 'NORWAY',:country_code =>'NO')                                       
Country.create(:country_name => 'OMAN',:country_code =>'OM')                                         
Country.create(:country_name => 'PAKISTAN',:country_code =>'PK')                                     
Country.create(:country_name => 'PALAU',:country_code =>'PW')                                        
Country.create(:country_name => 'PALESTINIAN TERR. OCCUPIED',:country_code =>'PS')                   
Country.create(:country_name => 'PANAMA',:country_code =>'PA')                                       
Country.create(:country_name => 'PAPUA NEW GUINEA',:country_code =>'PG')                             
Country.create(:country_name => 'PARAGUAY',:country_code =>'PY')                                     
Country.create(:country_name => 'PERU',:country_code =>'PE')                                         
Country.create(:country_name => 'PHILIPPINES',:country_code =>'PH')                                  
Country.create(:country_name => 'PITCAIRN',:country_code =>'PN')                                     
Country.create(:country_name => 'POLAND',:country_code =>'PL')                                       
Country.create(:country_name => 'PORTUGAL',:country_code =>'PT')                                     
Country.create(:country_name => 'PUERTO RICO',:country_code =>'PR')                                  
Country.create(:country_name => 'QATAR',:country_code =>'QA')                                        
Country.create(:country_name => 'ROMANIA',:country_code =>'RO')                                      
Country.create(:country_name => 'RUSSIAN FEDERATION',:country_code =>'RU')                           
Country.create(:country_name => 'RWANDA',:country_code =>'RW')                                       
Country.create(:country_name => 'R?UNION',:country_code =>'RE')                                      
Country.create(:country_name => 'SAINT HELENA',:country_code =>'SH')                                 
Country.create(:country_name => 'SAINT KITTS AND NEVIS',:country_code =>'KN')                        
Country.create(:country_name => 'SAINT LUCIA',:country_code =>'LC')                                  
Country.create(:country_name => 'SAINT PIERRE & MIQUELON',:country_code =>'PM')                      
Country.create(:country_name => 'SAMOA',:country_code =>'WS')                                        
Country.create(:country_name => 'SAN MARINO',:country_code =>'SM')                                   
Country.create(:country_name => 'SAO TOME AND PRINCIPE',:country_code =>'ST')                        
Country.create(:country_name => 'SAUDI ARABIA',:country_code =>'SA')                                 
Country.create(:country_name => 'SCOTLAND',:country_code =>'SQ')                                     
Country.create(:country_name => 'SENEGAL',:country_code =>'SN')                                      
Country.create(:country_name => 'SERBIA',:country_code =>'RS')                                       
Country.create(:country_name => 'SEYCHELLES',:country_code =>'SC')                                   
Country.create(:country_name => 'SIERRA LEONE',:country_code =>'SL')                                 
Country.create(:country_name => 'SINGAPORE',:country_code =>'SG')                                    
Country.create(:country_name => 'SLOVAKIA',:country_code =>'SK')                                     
Country.create(:country_name => 'SLOVENIA',:country_code =>'SI')                                     
Country.create(:country_name => 'SOLOMON ISLANDS',:country_code =>'SB')                              
Country.create(:country_name => 'SOMALIA',:country_code =>'SO')                                      
Country.create(:country_name => 'SOUTH AFRICA',:country_code =>'ZA')                                 
Country.create(:country_name => 'SPAIN',:country_code =>'ES')                                        
Country.create(:country_name => 'SRI LANKA',:country_code =>'LK')                                    
Country.create(:country_name => 'ST VINCENT & The GRENADINES',:country_code =>'VC')                  
Country.create(:country_name => 'SURINAME',:country_code =>'SR')                                     
Country.create(:country_name => 'SVALBARD AND JAN MAYEN',:country_code =>'SJ')                       
Country.create(:country_name => 'SWAZILAND',:country_code =>'SZ')                                    
Country.create(:country_name => 'SWEDEN',:country_code =>'SE')                                       
Country.create(:country_name => 'SWITZERLAND',:country_code =>'CH')                                  
Country.create(:country_name => 'SYRIAN ARAB REPUBLIC',:country_code =>'SY')                         
Country.create(:country_name => 'TAIWAN, PROVINCE OF CHINA',:country_code =>'TW')                    
Country.create(:country_name => 'TAJIKISTAN',:country_code =>'TJ')                                   
Country.create(:country_name => 'TANZANIA, UNITED REPUBLIC OF',:country_code =>'TZ')                 
Country.create(:country_name => 'THAILAND',:country_code =>'TH')                                     
Country.create(:country_name => 'TIMOR-LESTE',:country_code =>'TL')                                  
Country.create(:country_name => 'TOGO',:country_code =>'TG')                                         
Country.create(:country_name => 'TOKELAU',:country_code =>'TK')                                      
Country.create(:country_name => 'TONGA',:country_code =>'TO')                                        
Country.create(:country_name => 'TRINIDAD AND TOBAGO',:country_code =>'TT')                          
Country.create(:country_name => 'TUNISIA',:country_code =>'TN')                                      
Country.create(:country_name => 'TURKEY',:country_code =>'TR')                                       
Country.create(:country_name => 'TURKMENISTAN',:country_code =>'TM')                                 
Country.create(:country_name => 'TURKS AND CAICOS ISLANDS',:country_code =>'TC')                     
Country.create(:country_name => 'TUVALU',:country_code =>'TV')                                       
Country.create(:country_name => 'UGANDA',:country_code =>'UG')                                       
Country.create(:country_name => 'UKRAINE',:country_code =>'UA')                                      
Country.create(:country_name => 'UNITED ARAB EMIRATES',:country_code =>'AE')                         
Country.create(:country_name => 'UNITED KINGDOM',:country_code =>'GB')                               
Country.create(:country_name => 'UNITED STATES',:country_code =>'US')                                
Country.create(:country_name => 'URUGUAY',:country_code =>'UY')                                      
Country.create(:country_name => 'US MINOR OUTLYING ISLANDS',:country_code =>'UM')                    
Country.create(:country_name => 'UZBEKISTAN',:country_code =>'UZ')                                   
Country.create(:country_name => 'VANUATU',:country_code =>'VU')                                      
Country.create(:country_name => 'VENEZUELA',:country_code =>'VE')                                    
Country.create(:country_name => 'VIET NAM',:country_code =>'VN')                                     
Country.create(:country_name => 'VIRGIN ISLANDS, BRITISH',:country_code =>'VG')                      
Country.create(:country_name => 'VIRGIN ISLANDS, U.S.',:country_code =>'VI')                         
Country.create(:country_name => 'WALLIS AND FUTUNA',:country_code =>'WF')                            
Country.create(:country_name => 'WESTERN SAHARA',:country_code =>'EH')                               
Country.create(:country_name => 'YEMEN',:country_code =>'YE')                                        
Country.create(:country_name => 'ZAMBIA',:country_code =>'ZM')                                       
Country.create(:country_name => 'ZIMBABWE',:country_code =>'ZW')                                     
    
  end

  def self.down
    drop_table :countries
  end
end
